### ISSUE TITLE
Unable to fetch "NIST Framework for Improving Critical Infrastructure Cybersecurity Version 1.1"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton-nist#11]
"NIST Framework for Improving Critical Infrastructure Cybersecurity Version 1.1" is a `csrc-white-paper`, it can be found on NIST's site:

<img width="702" alt="Screen Shot 2019-04-17 at 10 31 25 AM" src="https://user-images.githubusercontent.com/11865/56256594-f54c8000-60fb-11e9-8b9b-737ac89f39aa.png">

And has a full page of information:

<img width="734" alt="Screen Shot 2019-04-17 at 10 31 34 AM" src="https://user-images.githubusercontent.com/11865/56256598-fc738e00-60fb-11e9-9f5c-dd7f59999bda.png">

(Notice the `CSWP` in the DOI link, it is a `csrc-white-paper`)

However, in NistBib it cannot return this document.

@andrew2net can you please help fix this? Thanks!

**Comment by opoudjis** [comment]
Ronald, does this document even have an identifier? If not, do we expect nistbib to retrieve by... title search?

**Comment by andrew2net** [comment]
@ronaldtse it sorts search results by release dates. I can try to sort by relevance but in this case, it also gives many results which we should filter somehow
<img width="1035" alt="Снимок экрана 2019-05-07 в 11 59 16" src="https://user-images.githubusercontent.com/5623890/57291688-3236e180-70c0-11e9-9205-d426274cf44f.png">

**Comment by opoudjis** [comment]
... That's just peachy. :-/

By default, I'd ignore any Withdrawn documents, and fetch the first available ("most relevant") final document.

**Comment by ronaldtse** [comment]
Agree with @opoudjis .

**Comment by opoudjis** [comment]
The document is now being fetched (for better or worst), and is in fact now an RSpec test case. It has spawned #17 and #19. Therefore this ticket no longer needs to be open.
