### ISSUE TITLE
Rendering of NIST White Paper reference, always prioritize fetching final instead of draft

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton-nist#19]
Using the following reference item:

```adoc
* [[[NISTCSF11,NIST Framework for Improving Critical Infrastructure Cybersecurity Version 1.1]]], _NIST Framework for Improving Critical Infrastructure Cybersecurity Version 1.1_
```

1. The document type is rendering in lowercase "nist" instead of "NIST"
2. It's getting the 2nd Draft rather than the final.

<img width="636" alt="Screen Shot 2019-05-27 at 10 37 48 PM" src="https://user-images.githubusercontent.com/11865/58426773-0fe92000-80d0-11e9-8f9d-6c4793006d96.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/relaton-nist/issues/17#issuecomment-496233868_

**Comment by opoudjis** [comment]
The two are completely different issues. Fetching the 2nd draft remains an issue here. The prefixing of "nist" is a separate issue.

**Comment by ronaldtse** [comment]
@andrew2net also, the "type" is wrong -- this is a "white-paper" not a "standard". See the Relaton XML cache attached.

[nist_framework_for_improving_critical_infrastructure_cybersecurity_version_1.1.xml.zip](https://github.com/metanorma/relaton-nist/files/3224228/nist_framework_for_improving_critical_infrastructure_cybersecurity_version_1.1.xml.zip)

**Comment by opoudjis** [comment]
Ronald, you're behind.

`bibitem@type` is now "standard" for *all* of Relaton. That is because document types are idiosyncratic to each flavour.

The type for a specific standard is bibdata/ext/doctype.

If the document type is going to be referenced in a citation, it must NOT be modelled as document type. It must be modelled as a series.

**Comment by opoudjis** [comment]
Note that #124 has also fixed this so that "White Paper" is populated in ext/doctype, which was the other issue raised here.

**Comment by ronaldtse** [comment]
@opoudjis just to confirm, is @andrew2net going to take care of this?

**Comment by andrew2net** [comment]
@ronaldtse I'm going but have a lot of tasks. Feel free to prioritize tasks in my todo and in progress lists.

**Comment by ronaldtse** [comment]
@andrew2net already done :wink:

**Comment by opoudjis** [comment]
Yes, I wasn't offering to take this one on.
