### ISSUE TITLE
Review NIST JSON

### ISSUE THREAD

**Issue by opoudjis** [metanorma/relaton-nist#23]
As published in https://github.com/metanorma/relaton-nist/issues/20

**Comment by opoudjis** [comment]
* The document class (Information Security, Computer Security), `title[@type = "document-class"]`, is not captured, other than as a keyword.
* The contact email is not captured.
* The docnumber will have to be extracted from the NIST document identifier.
* We currently don't model nicknames, and are unlikely to do anything with them.

These are not serious enough to impact rendering of citations, and these look to be sound mappings.

**Comment by ronaldtse** [comment]
> * The document class (Information Security, Computer Security), `title[@type = "document-class"]`, is not captured, other than as a keyword.
> * The contact email is not captured.

These two items are not in stored in the CSRC database, so it's not feasible to obtain them. Either way, both of these elements are not needed in rendering.
