### ISSUE TITLE
Travis for relaton-nist and relaton failing on VCR

### ISSUE THREAD

**Issue by opoudjis** [metanorma/relaton-nist#25]
https://travis-ci.com/metanorma/relaton-nist/jobs/208319499

````
An HTTP request has been made that VCR does not know how to handle:
  GET https://csrc.nist.gov/publications/detail/white-paper/2018/04/16/cybersecurity-framework-v11/final
````

**Comment by opoudjis** [comment]
Also failing for relaton Travis:

https://travis-ci.org/metanorma/relaton/jobs/546092095

````
An HTTP request has been made that VCR does not know how to handle:
  GET https://csrc.nist.gov/publications/detail/fips/140/1/archive/1994-01-11
````

The fail seems to be specific to Linux rather than OSX.

**Comment by andrew2net** [comment]
@opoudjis fixed, but it needs to be rereleased. There is sorting of hits by status in this gem. But if statuses are equal then result different for Linux and Mac. For White Papers, we need to add sorting by relevance. I've also added a release date to sorting function.

**Comment by opoudjis** [comment]
I'd rather wait until the next regular release, in a week or two, unless this is mission-critical. @ronaldtse?

**Comment by andrew2net** [comment]
@opoudjis it needs more work with sorting. In some cases, it doesn't work correctly.

**Comment by andrew2net** [comment]
@opoudjis fixed relevant sorting. I think we need to release these last changes because of it influent on White Pages search. White Pages don't have code so we can't filter hits by code. I added function to sort hits by most relevant titles.

**Comment by ronaldtse** [comment]
Yes, it's been released yesterday, I confirm that it works. Thanks!
